name: workflow

on: 
  schedule:
    - cron:  "25 10 * * *"

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: install requirements.txt 
      run: pip3 install -r requirements.txt
    
    - name: run main.py
      run: python3 main.py
      
    - name: set git options
      run : |
        git config user.name "m0zu"
        git config user.email "m0zurillex@gmail.com"
        git remote set-url origin https://0x0u:${{ secrets.GITHUB_PASS }}@github.com/0x0u/test_ghaction
    
    - name: run opt_git.py
      run: python3 opt_git.py
